# Generated by Django 4.1.1 on 2022-10-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0003_rename_descriptions_home_descriptions_home_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='status',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
