# Generated by Django 4.1.1 on 2022-10-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0004_sensor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='ip_sensor',
            field=models.GenericIPAddressField(protocol='IPv4', unique=True),
        ),
    ]
