# Generated by Django 4.0.8 on 2022-10-16 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0005_alter_sensor_ip_sensor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='status',
            new_name='status_sensor',
        ),
    ]
